spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/user-management-demo?authSource=admin&readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=false
      auto-index-creation: false